language: node_js
node_js:
- stable
script:
- npm run lint
- npm test
deploy:
  api_key:
    secure: WsmB1d930GAUAk/NJt2ZY3oLtTyZmB+43krCzB5cDtbaXeIy/he6G113/9EKMMMekZBan7SxDC+lRspSEoJJsRIEV49rKRJE4hw8AB7J0aGbPbfY5BKWRUYDnZq8IGuXddCvD1FTwivF6iuMCeT9sZwP6VC9+WStFFO2Nr5lCrEK+laHUxecUGsE4CbWG2Cnn43UKa40E/nIMT//6Et5Gq86uDw51zdYxXABJV1+Pd+yCoITf8j+BhjOVa7SRH8CZ/VwCSFM+g9hEfGfuWBiSlfydZ0rXFR4VHD7OZGam1A9DIZPPTyL1H8l10KoFsB4lmVTGbNsb7eFkdfdV2+x3/iVP0a54n48uXKlWsoGECIDLdMLNrnBE4M+vC9emLmA2zLt1HM3jiEu4YSyMsLha5wDg+VR7STXaf+0zHlTuuxZ50r5HAkEjQ3UB6bnsboqTL0fAjh4UnOO5VDJnrvQByYf9ptkP5w4K0ReSHNkQ9oox0gE9WbkjiC5JBWqcBPiHZaWdgs+Nn2MniznOMuH4WdM6575AORBTmoBEoP71jS2Pm7INcwI5lTBoftvXYBjLefHAMaxtmGtBoDmqECJjtXI3q4TOUz6P2giqL2s3HyrVnc4yV8pU6dQaDZcVbPTkBYIqp4rd3EMSYXYVXG6dhQ8OKOev2N1GOWbrCUOYWQ=
